name: pepper-openpose
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=10.0.1
  - py-opencv=3.4.2
  - python=3.5.6
  - pip:
    - imageio==2.11.1
    - numpy==1.18.5
    - opencv-contrib-python==4.2.0.34
    - qi==3.0.0
    - tk==0.1.0
    - torch==1.5.1
    - torchvision==0.6.1


